### ISSUE TITLE
Install Error on Aras Innovator Version 11.0 SP9  Build: 6549

### ISSUE THREAD

**Issue by weekaung** [ArasLabs/collab-folders#1]
Hi,
I tried installing the latest version of this software onto Aras Innovator Version 11.0 SP9  Build: 6549.
However, I am getting errors and is unusable.
Will you be releasing a fix to the latest Aras Innovator Version 11.0 SP9.
I will appreciate your help.
Thanks,
David.
![selection_003](https://user-images.githubusercontent.com/24662880/28005594-11d16c5c-657e-11e7-833a-f70219a01f3a.png)

**Comment by EliJDonahue** [comment]
Hi David,
We have received several requests regarding this project, so I am currently working on upgrading it to support Aras 11 SP9. I aim to have the update posted by the end of the week.

**Comment by weekaung** [comment]
Hi Eli,
That's great news. Thank you for your help.
Will be looking forward to the fix.
Regards, David.

**Comment by EliJDonahue** [comment]
Hi David,
Import issues with Aras 11 SP9 should be resolved in [release v5.4](https://github.com/ArasLabs/collab-folders/releases/tag/v5.4).

**Comment by weekaung** [comment]
Hi Eli,
Excellent, thank you for the update. Will try out the new version.
Regards, David.
