### ISSUE TITLE
collab_folder error on my side

### ISSUE THREAD

**Issue by jenli720** [ArasLabs/collab-folders#2]
Hi All,

I just imported Collab-Folders project into my Aras platform, then I got this error when I hit the All Top Folders on TOC (please see the attached screenshot), Is there any configurations I need to set up during the import or any ideas? Thanks very much.
![3](https://user-images.githubusercontent.com/40969519/42426056-3798c5b6-8314-11e8-808b-b695f0df02f3.JPG)

FYI, 
·        Which version of the project you’re using
 --**V5.5**

·        Which version of Innovator you’re using
 **--Version11 SP12，,Im not sure whether the version caused the error or not , since at least I import the project successfully.** 

·        Which browser(s) reproduce this issue
**-- All browsers**
·        Which language pack(s) you are using
**--English**

 

Best,
Jen Li

**Comment by xzf16** [comment]
I think SP12 has not bee supported yet.

**Comment by rlaudenbach** [comment]
This is correct.  I’m looking into migration of QueryBuilder and TreeGridView for next versions as time permits.
Not a  high priority for me at the moment.

BR
Rolf Laudenbach

**Comment by EliJDonahue** [comment]
Hi all,

One of our Aras Community Forum members found [a solution to this issue](http://community.aras.com/en/forums/topic/araslabs-collab-folders-2). Here is the content from his post:

> Found out all by myself. Sharing here for benefit of others. Works for both Version 11 SP11 and SP12 too.
> 
> Although this instruction is part of installation notes, it was not explicit.
> 
> Go to variables and set values for the following:
> 
> tGridCfg cFolder
> Client/Solutions/ItemFolders/xml/cFolderStructureConfig.xml
> 
> tGridCfg cFolder Template
> Client/Solutions/ItemFolders/xml/cFolderStructureConfig.xml
> 
> tGridCfg Project
> Client/Solutions/ItemFolders/xml/cFolderStructureConfig.xml
> 
> tGridCfg Root Folders TOC
> Client/Solutions/ItemFolders/xml/cFolderStructureConfig.xml
> 
> tGridCfg User Folders TOC
> Client/Solutions/ItemFolders/xml/cFolderStructureConfig.xml

Hopefully we can get the install steps updated soon. 

Eli

**Comment by asebastian-aras** [comment]
Submitted #4 to note this within the README.

**Comment by EliJDonahue** [comment]
Readme has been updated. Closing this issue.
