### ISSUE TITLE
Upgrade to support 11 SP14

### ISSUE THREAD

**Issue by EliJDonahue** [ArasLabs/collab-folders#3]
We've received requests to upgrade this project to support Aras 11 SP14. See Issue #2 for first error to fix.

**Comment by asebastian-aras** [comment]
Hi @nidheeshv , this issue was very vague, but with issue #2 being complete, the upgrade is complete. After pull request #9 and #10 this issue should be finished and closed.

**Comment by EliJDonahue** [comment]
Just waiting on an answer from the original project author regarding issue #7. Then that issue can be resolved and a new release added to support SP15.

**Comment by EliJDonahue** [comment]
@asebastian-aras - now that all pull requests are closed, you can update the readme with a new release that adds SP14 support. Once the new release is live, you can close out this issue.

**Comment by EliJDonahue** [comment]
Issue resolved by PR #11
