### ISSUE TITLE
Upgrade import/READ_ME.txt

### ISSUE THREAD

**Issue by asebastian-aras** [ArasLabs/collab-folders#6]
Import instructions are outdated. The imports work sequentially, so this just involves changing the text file to match up with the order of the folders, ensuring the names are correct, and moving the ones marked "optional" to the bottom.

**Comment by EliJDonahue** [comment]
@asebastian-aras - Have you tested importing the optional packages at the end works? (Rather than importing them in the order they're written)

**Comment by EliJDonahue** [comment]
@asebastian-aras - Ok, should we just remove that package then?

**Comment by EliJDonahue** [comment]
We can resolve the optional package imports as part of the fix for issue #7 after we hear back from Rolf. In the meantime, @nicoffee's PR will be fine. Just waiting on one tweak before merging PR #8 and closing this issue.

**Comment by EliJDonahue** [comment]
PR #8 is merged and this issue is complete.
